// Package main generated by 'freedom new-project raven'
package main

import (
	"context"
	"errors"
	"html"
	"net/http"
	"os"
	"path/filepath"
	_ "raven/backend/controller" //Implicit initialization controller
	"raven/backend/infra"
	"raven/backend/repository"
	_ "raven/backend/repository" //Implicit initialization repository
	"raven/backend/service"
	"raven/backend/vo"
	"raven/config"
	"strings"
	"sync"
	"time"

	"github.com/8treenet/freedom"
	"github.com/8treenet/freedom/infra/requests"
	"github.com/8treenet/freedom/middleware"
	"github.com/8treenet/iris/v12"

	"github.com/redis/go-redis/v9"
	"gorm.io/driver/mysql"
	"gorm.io/driver/postgres"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func main() {
	app := freedom.NewApplication()
	installMiddleware(app)

	if config.Get().System.Initialized {
		installDatabase(app)
		installRedis(app)
	}

	runner := app.NewRunner(config.Get().App.Other["listen_addr"].(string))
	frontend(app)
	app.InstallParty("/api")

	app.Run(runner, config.Get().App)
}

func installMiddleware(app freedom.Application) {
	app.InstallMiddleware(middleware.NewRecover())
	app.InstallMiddleware(middleware.NewTrace("x-request-id"))
	//One Loger per request New.
	app.InstallMiddleware(middleware.NewRequestLogger("x-request-id"))
	//The middleware output of the log line.
	app.Logger().Handle(middleware.DefaultLogRowHandle)

	//Install the Prometheus middleware.
	middle := middleware.NewClientPrometheus(config.Get().App.Other["service_name"].(string), freedom.Prometheus())
	requests.InstallMiddleware(middle)

	//HTTP request link middleware that controls the header transmission of requests.
	app.InstallBusMiddleware(middleware.NewBusFilter())

	if config.Get().Behavior.PreviewUser != "" {
		app.InstallMiddleware(newPreviewMiddleware())
	}
	if !config.Get().System.Initialized {
		app.InstallMiddleware(newInitCheckMiddleware())
	}
}

func newPreviewMiddleware() freedom.Handler {
	return func(ctx freedom.Context) {
		if ctx.Method() == "GET" {
			ctx.Next()
			return
		}
		msg := "Preview mode, write operations are not allowed"
		if config.Get().GetLanguage() == "zh" {
			msg = "当前为预览模式，无法执行写操作"
		}
		ctx.StatusCode(200)
		infra.JSONResponse{
			Code:  infra.Access_Denied,
			Error: errors.New(msg),
		}.Dispatch(ctx)
	}
}

func newInitCheckMiddleware() freedom.Handler {
	return func(ctx freedom.Context) {
		path := ctx.Path()
		if strings.HasPrefix(path, "/api/") && !strings.HasPrefix(path, "/api/install") {
			ctx.StatusCode(200)
			infra.JSONResponse{
				Code:  infra.System_NotInit,
				Error: errors.New("system not initialized"),
			}.Dispatch(ctx)
			return
		}
		ctx.Next()
	}
}

func installDatabase(app freedom.Application) {
	app.InstallDB(func() interface{} {
		dbConf := config.Get().DB
		dbConfAddr := dbConf.Addr
		dbType := config.Get().System.DBType

		var dialector gorm.Dialector
		switch dbType {
		case "mysql":
			dialector = mysql.Open(dbConfAddr)
		case "pg":
			dialector = postgres.Open(dbConfAddr)
		default: // sqlite
			dbConfAddr = config.Get().Paths.SqliteDB
			dialector = sqlite.Open(dbConfAddr)
		}

		db, err := gorm.Open(dialector, &gorm.Config{})
		if err != nil {
			freedom.Logger().Fatal(err.Error())
		}

		sqlDB, err := db.DB()
		if err != nil {
			freedom.Logger().Fatal(err.Error())
		}

		sqlDB.SetMaxOpenConns(dbConf.MaxOpenConns)
		sqlDB.SetMaxIdleConns(dbConf.MaxIdleConns)
		if dbConf.ConnMaxLifeTime > 0 {
			sqlDB.SetConnMaxLifetime(time.Duration(dbConf.ConnMaxLifeTime) * time.Second)
		}
		if dbConf.ConnMaxIdleTime > 0 {
			sqlDB.SetConnMaxIdleTime(time.Duration(dbConf.ConnMaxIdleTime) * time.Second)
		}

		if err = repository.Merge(db); err != nil {
			freedom.Logger().Fatal(err.Error())
		}
		return db
	})
}

func installRedis(app freedom.Application) {
	app.InstallRedis(func() (client redis.Cmdable) {
		if config.Get().System.CacheType == "redis" {
			cfg := config.Get().Redis
			opt := &redis.Options{
				Addr:            cfg.Addr,
				Password:        cfg.Password,
				DB:              cfg.DB,
				MaxRetries:      cfg.MaxRetries,
				PoolSize:        cfg.PoolSize,
				ReadTimeout:     time.Duration(cfg.ReadTimeout) * time.Second,
				WriteTimeout:    time.Duration(cfg.WriteTimeout) * time.Second,
				ConnMaxIdleTime: time.Duration(cfg.IdleTimeout) * time.Second,
				ConnMaxLifetime: time.Duration(cfg.MaxConnAge) * time.Second,
				PoolTimeout:     time.Duration(cfg.PoolTimeout) * time.Second,
			}
			redisClient := redis.NewClient(opt)
			if e := redisClient.Ping(context.Background()).Err(); e != nil {
				freedom.Logger().Fatal(e.Error())
			}
			return redisClient
		}
		return infra.NewCacheWrapper(5*time.Minute, 10*time.Minute)
	})
}

func frontend(app freedom.Application) {
	app.Iris().HandleDir("/assets", filepath.Join(config.Get().Paths.FrontendDir, "assets"))
	app.Iris().HandleDir("/logos", filepath.Join(config.Get().Paths.FrontendDir, "logos"))
	app.Iris().HandleDir("/upload", config.Get().GetUploadDir())
	app.Iris().Get("/", func(ctx freedom.Context) {
		ctx.ServeFile(filepath.Join(config.Get().Paths.FrontendDir, "index.html"), false)
	})
	app.Iris().Get("/share/{shareId:string}", serveSharePage)
	app.Iris().OnErrorCode(iris.StatusNotFound, func(ctx iris.Context) {
		path := ctx.Path()
		// 如果是 API 请求或者明确带有点（.js, .css）的静态文件真的丢了，返回标准 404
		if strings.HasPrefix(path, "/api") || strings.Contains(path, ".") {
			ctx.StatusCode(http.StatusNotFound)
			ctx.WriteString("404 Not Found")
			return
		}
		ctx.ServeFile(config.Get().Paths.FrontendDir+"/index.html", false)
	})
	app.Iris().Get("/favicon.svg", func(ctx iris.Context) {
		ctx.ServeFile(filepath.Join(config.Get().Paths.FrontendDir, "favicon.svg"), false)
	})
}

var (
	indexHTMLOnce  sync.Once
	indexHTMLBytes []byte
	indexHTMLErr   error
)

func loadIndexHTML() []byte {
	indexHTMLOnce.Do(func() {
		indexHTMLBytes, indexHTMLErr = os.ReadFile(filepath.Join(config.Get().Paths.FrontendDir, "index.html"))
	})
	if indexHTMLErr != nil {
		return nil
	}
	return indexHTMLBytes
}

func serveBareIndex(ctx iris.Context) {
	b := loadIndexHTML()
	if b == nil {
		ctx.StatusCode(http.StatusNotFound)
		ctx.WriteString("404 Not Found")
		return
	}
	ctx.ContentType("text/html; charset=utf-8")
	ctx.StatusCode(http.StatusOK)
	_, _ = ctx.Write(b)
}

func serveSharePage(ctx iris.Context) {
	shareId := ctx.Params().Get("shareId")
	indexBytes := loadIndexHTML()
	if indexBytes == nil {
		serveBareIndex(ctx)
		return
	}

	var data *vo.ShareOGData
	var callErr error
	_ = freedom.ServiceLocator().Call(func(s *service.ShareLinkService) error {
		data, callErr = s.GetShareOGData(shareId, ctx)
		return callErr
	})
	if callErr != nil || data == nil {
		serveBareIndex(ctx)
		return
	}

	page := string(indexBytes)
	if idx := strings.Index(page, "<title>"); idx >= 0 {
		end := strings.Index(page[idx:], "</title>")
		if end >= 0 {
			page = page[:idx] + "<title>" + html.EscapeString(data.Title) + " · Raven</title>" + page[idx+end+len("</title>"):]
		}
	}
	page = strings.Replace(page, "</head>", service.BuildOGHTML(data)+"</head>", 1)

	ctx.ContentType("text/html; charset=utf-8")
	ctx.StatusCode(http.StatusOK)
	_, _ = ctx.WriteString(page)
}
