// Package infra generated by 'freedom new-project goraven'
package infra

import (
	"encoding/json"
	"errors"
	"fmt"
	"strconv"

	"github.com/8treenet/freedom"
)

// PageResponse 通用分页响应
/*
	return infra.JSONResponse{Object: infra.PageResponse{
		List:       list,
		TotalPage:  totalPage,
		TotalCount: totalCount,
		Page:       req.Page,
		PageSize:   req.PageSize,
	}}
*/

type PageResponse struct {
	List       interface{} `json:"list"`               // 数据列表
	TotalPage  int         `json:"totalPage"`          // 总页数
	TotalCount int         `json:"totalCount"`         // 总记录数
	Page       int         `json:"page,omitempty"`     // 当前页码
	PageSize   int         `json:"pageSize,omitempty"` // 每页条数
}

// JSONResponse .
type JSONResponse struct {
	Code      int
	Error     error
	Object    interface{}
	LogOutput bool
}

type ResBodyObject struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

// Dispatch .
func (jrep JSONResponse) Dispatch(ctx freedom.Context) {
	var content []byte
	var body ResBodyObject
	body.Data = jrep.Object
	body.Code = jrep.Code

	if jrep.Error != nil {
		body.Msg = jrep.Error.Error()
	}

	if jrep.Error != nil && body.Code == 0 {
		if werr, ok := jrep.Error.(*wrapperError); ok {
			body.Code = werr.code
		}
	}

	if jrep.Error != nil && body.Code == 0 {
		body.Code = 400
	}

	if content, jrep.Error = json.Marshal(body); jrep.Error != nil {
		content = []byte(jrep.Error.Error())
	}

	ctx.Values().Set("code", strconv.Itoa(body.Code))
	if jrep.LogOutput {
		ctx.Values().Set("response", string(content))
	}

	ctx.ContentType("application/json")
	ctx.StatusCode(200)
	if _, err := ctx.Write(content); err != nil {
		freedom.Logger().Error("JSONResponse dispatch error: %v", err)
	}
}

// WrapperError
// e = infra.WrapperError(infra.Access_Disable, "账户禁用")
func WrapperError(code int, content string) error {
	return &wrapperError{err: errors.New(content), code: code}
}

func WrapperErrorf(code int, contentFormat string, a ...interface{}) error {
	return &wrapperError{err: fmt.Errorf(contentFormat, a...), code: code}
}

type wrapperError struct {
	err  error
	code int
}

// Error.
func (e *wrapperError) Error() string {
	return e.err.Error()
}
