package seed

import "goraven/backend/po"

var RecommendMCPEndpoints = []po.MCPEndpoint{
	{
		Name:        "github",
		DisplayName: "github",
		Icon:        "git-branch",
		Description: " Repository management, file operations, and GitHub API integration.",
		Transport:   "Stdio",
		StdioType:   "npx",
		StdioEnv:    `["GITHUB_PERSONAL_ACCESS_TOKEN=<YOUR_TOKEN>"]`,
		StdioArgs:   `["@modelcontextprotocol/server-github"]`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "",
	},
	{
		Name:        "postgresql",
		DisplayName: "PostgreSQL",
		Icon:        "database",
		Description: "Read-only database access with schema inspection.",
		Transport:   "Stdio",
		StdioType:   "npx",
		StdioEnv:    `[]`,
		StdioArgs:   `["@modelcontextprotocol/server-postgres","postgresql://localhost/mydb"]`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "",
	},
	{
		Name:        "puppeteer",
		DisplayName: "puppeteer",
		Icon:        "monitor",
		Description: "Browser automation and web scraping.",
		Transport:   "Stdio",
		StdioType:   "npx",
		StdioEnv:    `[]`,
		StdioArgs:   `["@modelcontextprotocol/server-puppeteer"]`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "",
	},
	{
		Name:        "firecrawl",
		DisplayName: "Firecrawl",
		Icon:        "radar",
		Description: "Official Firecrawl MCP Server - Adds powerful web scraping to Cursor, Claude and any other LLM clients.",
		Transport:   "Stdio",
		StdioType:   "npx",
		StdioEnv:    `["FIRECRAWL_API_KEY=<YOUR_TOKEN>"]`,
		StdioArgs:   `["firecrawl-mcp"]`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "",
	},
	{
		Name:        "brave-search",
		DisplayName: "BraveSearch",
		Icon:        "file-search",
		Description: "An MCP server implementation that integrates the Brave Search API",
		Transport:   "Stdio",
		StdioType:   "npx",
		StdioEnv:    `["BRAVE_API_KEY=<YOUR_API_KEY_HERE>"]`,
		StdioArgs:   `["@brave/brave-search-mcp-server"]`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "",
	},
	{
		Name:        "aliyun-zimage",
		DisplayName: "AliyunZImage",
		Icon:        "image",
		Description: "Z-Image-Turbo is a highly efficient image generation model that ranks #1 among open-source text-to-image models on the Artificial Analysis benchmark. With only 6B parameters and 8 inference steps, it delivers photo-realistic images comparable to large commercial models, with strong bilingual (Chinese/English) text rendering, complex semantic understanding, and diverse subject generation.",
		Transport:   "StreamableHttp",
		HttpUrl:     "https://dashscope.aliyuncs.com/api/v1/mcps/zimage/mcp",
		HttpHeader:  `{"Authorization":"Bearer ${DASHSCOPE_API_KEY}"}`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "Please register an API key at Aliyun Bailian (https://bailian.console.aliyun.com/) and set it as DASHSCOPE_API_KEY.",
	},
	{
		Name:        "aliyun-web-search",
		DisplayName: "AliyunWebSearch",
		Icon:        "zap",
		Description: "Real-time full-stack internet information retrieval built on Tongyi Lab's Text-Embedding, GTE-reRank, query rewriting, and search judgment models. Combines professional search engineering frameworks with real-time retrieval tools to improve LLM answer accuracy and timeliness.",
		Transport:   "StreamableHttp",
		HttpUrl:     "https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/mcp",
		HttpHeader:  `{"Authorization":"Bearer ${DASHSCOPE_API_KEY}"}`,
		Status:      po.MCPEndpointStatusEnabled,
		Remark:      "Please register an API key at Aliyun Bailian (https://bailian.console.aliyun.com/) and set it as DASHSCOPE_API_KEY.",
	},
}
