package seed

import "goraven/backend/po"

// SkillMarketSeeds contains the default skill market seed data.
var SkillMarketSeeds = []po.SkillMarket{
	{
		Name:        "skill-creator",
		Description: "Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Claude's capabilities with specialized knowledge, workflows, or tool integrations.",
		Icon:        "zap",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "skill-creator",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "skill-vetter",
		Description: "Security-first skill vetting for AI agents. Use before installing any skill from ClawdHub, GitHub, or other sources. Checks for red flags, permission scope, and suspicious patterns.",
		Icon:        "zap",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "skill-vetter",
		CategoryId:  3,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "nano-pdf",
		Description: "Edit PDFs with natural-language instructions using the nano-pdf CLI.",
		Icon:        "spell-check",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "nano-pdf",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "self-improvement",
		Description: "Captures learnings, errors, and corrections to enable continuous improvement. Use when: (1) A command or operation fails unexpectedly, (2) User corrects Claude ('No, that's wrong...', 'Actually...'), (3) User requests a capability that doesn't exist, (4) An external API or tool fails, (5) Claude realizes its knowledge is outdated or incorrect, (6) A better approach is discovered for a recurring task. Also review learnings before major tasks.",
		Icon:        "mail",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "self-improving-agent",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "excel-xlsx",
		Description: "Create, inspect, and edit Microsoft Excel workbooks and XLSX files with reliable formulas, dates, types, formatting, recalculation, and template preservation. Use when (1) the task is about Excel, `.xlsx`, `.xlsm`, `.xls`, `.csv`, or `.tsv`; (2) formulas, formatting, workbook structure, or compatibility matter; (3) the file must stay reliable after edits.",
		Icon:        "bar-chart-3",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "excel-xlsx",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "word-docx",
		Description: "Create, inspect, and edit Microsoft Word documents and DOCX files with reliable styles, numbering, tracked changes, tables, sections, and compatibility checks. Use when (1) the task is about Word or `.docx`; (2) the file includes tracked changes, comments, fields, tables, templates, or page layout constraints; (3) the document must survive round-trip editing without formatting drift.",
		Icon:        "text",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "word-docx",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
	{
		Name:        "pptx",
		Description: "Presentation creation, editing, and analysis. When Claude needs to work with presentations (.pptx files) for: (1) Creating new presentations, (2) Modifying or editing content, (3) Working with layouts, (4) Adding comments or speaker notes, or any other presentation tasks",
		Icon:        "zap",
		Source:      po.SkillSourceClawHub,
		SourceUrl:   "organize-messy-files-pptx",
		CategoryId:  1,
		Status:      po.SkillStatusEnabled,
		SortOrder:   0,
		Remark:      "",
	},
}
